version: '3'
services:
  haproxy_nginx:
    build:
      context: .
      dockerfile: Dockerfile.haproxy_nginx
    ports:
      - "8080:80"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - metrics_scraper

  metrics_scraper:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    ports:
      - "5000:5000"

