version: '3.8'

services:
  haproxy_nginx:
    image: pegasus2305/pratham:updated-version
    ports:
      - "80:80"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
